### ISSUE TITLE
cool project!

### ISSUE THREAD

**Issue by aquynh** [tsavola/wag#1]
wow, this looks like a nice tool! will you have a README with more info? 
and is there any screenshot?

keep it up, cheers.

**Comment by tsavola** [comment]
Thanks! Yeah, I should get around to writing some documentation now that I've validated the idea by completing a more or less working implementation.

This compiler is designed to serve the goals of my larger concept https://github.com/tsavola/gate (I should document that aswell). But there's no reason why it couldn't be used as standalone.
